# This is a basic workflow to help you get started with Actions

name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sphinx_version: ["", "~=4.0.0" "~=3.0.0"]
        python_version: ["3.6", "3.8", '3.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          pip install sphinx${{matrix.sphinx_version}} -r requirements.txt .
          # jinja2 broke on 2022-03-24
          # https://github.com/sphinx-doc/sphinx/issues/10291
          # https://github.com/sphinx-doc/sphinx/issues/10289
          # Unsure of long-term plan here.
          if [ -n "{{matrix.sphinx_version}}" ] ; then
              pip install "jinja2<3.1"
          fi
      - name: List dependency versions
        run: |
          python -V
          pip list

      # Runs a set of commands using the runners shell
      - name: Build and fail on errors
        run: |
          make html SPHINXOPTS="-W --keep-going -T -v"
